### ISSUE TITLE
[question] Are micro libraries allowed to include a css file?

### ISSUE THREAD

**Issue by pryley** [microjs/microjs.com#970]
I have a library that is < 5KB minified, it comes with a css file. Is this allowed?

Link: https://github.com/geminilabs/star-rating.js

**Comment by pineapplemachine** [comment]
I don't see any submissions with a css file so far, but I don't see why one couldn't be included. I do wonder if you can build a non-minified version of the css to use for the microjs listing, though, since in the repo I see only an `scss` file and a minified `css` file; sass files being nonstandard and the repo having a policy of only linking to code that wasn't already minified.

Also, I believe the automatic filter considers the total size of all files; I see that your minified source and css are close to 8kb together. You should check if the combined size when the files are gzipped is under 5kb to determine if the library can be listed on microjs. If that's the case, please feel free to create a PR for adding star-rating.

**Comment by pineapplemachine** [comment]
PR for star-rating made here: https://github.com/microjs/microjs.com/pull/974
